"""empty message

Revision ID: 7ddfec3f500d
Revises: 
Create Date: 2021-12-02 14:50:03.524992

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ddfec3f500d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installed_work_space',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slack_ws_id', sa.String(length=100), nullable=True),
    sa.Column('slack_ws_name', sa.String(length=100), nullable=True),
    sa.Column('enterprise_id', sa.String(), nullable=True),
    sa.Column('user_num', sa.Integer(), nullable=True),
    sa.Column('plan', sa.String(length=2000), nullable=True),
    sa.Column('free_expired_at', sa.DateTime(), nullable=True),
    sa.Column('plan_expired_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('installed_at', sa.DateTime(), nullable=True),
    sa.Column('channel_joined_at', sa.DateTime(), nullable=True),
    sa.Column('deepl_api_key', sa.String(length=100), nullable=True),
    sa.Column('postlimit', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('to_do',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('to_do')
    op.drop_table('user')
    op.drop_table('installed_work_space')
    # ### end Alembic commands ###
